Step #1 - Load in dataset (CSV file) using pandas package

In [76]:
import pandas as pd

In [77]:
df = pd.read_csv(r"C:\Users\graem\OneDrive\Documents\Algonquin\Fall Semester\CST8504 - AI Techniques\dir\heart_failure_clinical_records_dataset.csv")
df

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

Check current working directory, and change to desired working directory

In [78]:
import os

print("Before:", os.getcwd())

os.chdir('c:/Users/graem/OneDrive/Documents/Algonquin/Fall Semester/CST8504 - AI Techniques')

Before: c:\Users\graem\OneDrive\Documents\Algonquin\Fall Semester\CST8504 - AI Techniques

Step 2: Data Cleaning

First, it is important to make sure we do not have any duplicate instances

In [79]:
df.drop_duplicates()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

Good news: there were no duplicates!

Now we should check for missing observations

In [80]:
df.isna().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

Good news, we don't have any missing observations either!

In [81]:
df

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

Creating bins for age

In [82]:
age_edges = [0, 55, 65, 1000]
age_labels = ['40-55', '55-65', '65+']

# Create the new categorical variable
df['Age_Group'] = pd.cut(df['age'], bins=age_edges, labels=age_labels)

Creating bins for time

In [83]:
time_edges = [0, 60, 120, 180, 240, 300]
time_labels = ['0-2 Months', '2-4 Months', '4-6 Months', '6-8 Months', '8+ Months']

# Create the new categorical variable
df['Time_Group'] = pd.cut(df['time'], bins=time_edges, labels=time_labels)

Creating bins for EF

In [84]:
EF_edges = [0, 30, 40, 50, 100]
EF_labels = ['Critically Low', 'Very Low', 'Mildly Low', 'Normal']

# Create the new categorical variable
df['EF_Group'] = pd.cut(df['ejection_fraction'], bins=EF_edges, labels=EF_labels)

Creating bins for Creatinine levels

In [85]:
Creatinine_edges = [0, 0.7, 1.3, 100]
Creatinine_labels = ['Low', 'Normal', 'High']

# Create the new categorical variable
df['Creatinine_Group'] = pd.cut(df['serum_creatinine'], bins=Creatinine_edges, labels=Creatinine_labels)

Creating bins for Sodium levels

In [86]:
Sodium_edges = [0, 120, 124, 134, 145, 1000]
Sodium_labels = ['Severely Low', 'Moderately Low', 'Mildly Low', 'Normal', 'High']

# Create the new categorical variable
df['Sodium_Group'] = pd.cut(df['serum_sodium'], bins=Sodium_edges, labels=Sodium_labels)

Creating bins for Platelets

In [87]:
platelets_edges = [0, 150000, 450000, 1000000]
platelets_labels = ['Low', 'Normal', 'High']

# Create the new categorical variable
df['platelets_Group'] = pd.cut(df['platelets'], bins=platelets_edges, labels=platelets_labels)

Creating bins for creatinine phosphokinase

In [88]:
CPK_edges = [10, 120, 500, 5000, 1000000]
CPK_labels = ['Normal', 'Mildly high', 'Moderately high', 'Severely high']

# Create the new categorical variable
df['CPK_Group'] = pd.cut(df['creatinine_phosphokinase'], bins=CPK_edges, labels=CPK_labels)

In [89]:
df

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT,Age_Group,Time_Group,EF_Group,Creatinine_Group,Sodium_Group,platelets_Group,CPK_Group
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1,65+,0-2 Months,Critically Low,High,Mildly Low,Normal,Moderately high
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1,40-55,0-2 Months,Very Low,Normal,Normal,Normal,Severely high
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1,55-65,0-2 Months,Critically Low,Normal,Mildly Low,Normal,Mildly high
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1,40-55,0-2 Months,Critically Low,High,Normal,Normal,Normal
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1,55-65,0-2 Months,Critically Low,High,Severely Low,Normal,Mildly high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0,55-65,8+ Months,Very Low,Normal,Normal,Normal,Normal
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0,40-55,8+ Months,Very Low,Normal,Normal,Normal,Moderately high
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0,40-55,8+ Months,Normal,Normal,Normal,High,Moderately high
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0,40-55,8+ Months,Very Low,High,Normal,Low,Moderately high
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0,40-55,8+ Months,Mildly Low,High,Normal,Normal,Mildly high

In [90]:
df2 = df[['DEATH_EVENT', 'sex', 'smoking', 'diabetes', 'high_blood_pressure', 'anaemia', 'Age_Group', 'Time_Group', 'EF_Group', 'Creatinine_Group', 'Sodium_Group']]

In [91]:
df2

,DEATH_EVENT,sex,smoking,diabetes,high_blood_pressure,anaemia,Age_Group,Time_Group,EF_Group,Creatinine_Group,Sodium_Group
0,1,1,0,0,1,0,65+,0-2 Months,Critically Low,High,Mildly Low
1,1,1,0,0,0,0,40-55,0-2 Months,Very Low,Normal,Normal
2,1,1,1,0,0,0,55-65,0-2 Months,Critically Low,Normal,Mildly Low
3,1,1,0,0,0,1,40-55,0-2 Months,Critically Low,High,Normal
4,1,0,0,1,0,1,55-65,0-2 Months,Critically Low,High,Severely Low
...,...,...,...,...,...,...,...,...,...,...,...
294,0,1,1,1,1,0,55-65,8+ Months,Very Low,Normal,Normal
295,0,0,0,0,0,0,40-55,8+ Months,Very Low,Normal,Normal
296,0,0,0,1,0,0,40-55,8+ Months,Normal,Normal,Normal
297,0,1,1,0,0,0,40-55,8+ Months,Very Low,High,Normal
298,0,1,1,0,0,0,40-55,8+ Months,Mildly Low,High,Normal

Save datasets

In [92]:
df.to_csv('cleaned_full_dataset.csv', index=False)
df2.to_csv('cleaned_concise_dataset.csv', index=False)